### PR TITLE
Add SearchInput to users and rooms

### PR DESCRIPTION
**Pull request by dklimpel**
Add filter to search in `user_id` and room name.

### CODE REVIEW

**Comment by sm2x** [comment]
I get "Cannot read property 'users' of undefined" as soon as I cleared the search input field

**Comment by dklimpel** [comment]
> I get "Cannot read property 'users' of undefined" as soon as I cleared the search input field

I cannot reproduce this neither with FF 76/77 nor with Chrome 83.

**Comment by awesome-manuel** [comment]
Please wait for https://github.com/matrix-org/synapse/pull/7377

**Comment by CybotTM** [comment]
> Please wait for matrix-org/synapse#7377

seems to be merged.

**Comment by dklimpel** [comment]
Replaced by #83

**Pull request closed without merging**
