### PR TITLE
Add list of client connections per user

### PR DESCRIPTION
**Pull request by dklimpel**
List the result of `GET /_synapse/admin/v1/whois/<user_id>`

### CODE REVIEW

**Comment by awesome-manuel** [comment]
Also use `yarn fix` to fix the coding style.

**Comment by dklimpel** [comment]
Can you give a hint for yarn checks at Travis CI? I am get also errors at the current master.

**Comment by dklimpel** [comment]
In my opinion tabs are not a solution. Tabs are for grouping informations. But in this case the informations are nested, with different api request, and not grouped in one api request.

**Comment by dklimpel** [comment]
I have got it in tab. I will try to improve with icons.

**Pull request closed without merging**
