### PR TITLE
Add a new tab to user page with room memberships

### PR DESCRIPTION
**Pull request by dklimpel**
The admin API for user's room memberships is new in synapse v1.21.0.

### CODE REVIEW

**Comment by awesome-manuel** [comment]
I get HTTP 404 with `{"errcode":"M_NOT_FOUND","error":"User not found"}` for all users.

**Comment by dklimpel** [comment]
I did a new test. I am get HTTP 200 and in console:
```
dataProvider.js:205 getManyReference joined_rooms
dataProvider.js:7 httpClient https://server/_synapse/admin/v1/users/@testuser:server/joined_rooms
```

**Comment by awesome-manuel** [comment]
Which synapse version did you use?

**Comment by dklimpel** [comment]
Synapse v1.22.1.
The API is realeased in v1.21.0: https://github.com/matrix-org/synapse/blob/develop/CHANGES.md#features-3
https://github.com/matrix-org/synapse/issues/8306

**Comment by awesome-manuel** [comment]
Could it be a problem of users that are in no room (yet)?

**Comment by dklimpel** [comment]
Yes, you're right.

**Comment by dklimpel** [comment]
It is fixed in Synapse v1.23.0.
https://github.com/matrix-org/synapse/pull/8643

**Comment by dklimpel** [comment]
Related #100

**Pull request merged**
