### PR TITLE
feat: support SSO login

### LINKED ISSUE #56: SSO Login support
I'd like to manage a homeserver with SSO login, but this only seems to support password login?

### PR DESCRIPTION
**Pull request by Candinya**
Sorry for the latency. Finally it comes back now. Thanks for your patiences and sorry for the inconveniences I've caused.
Optimized a little (since last commit using force refresh to prevent further requests, now using `replaceState` to optimize the performance.) after I've gained more React develop experiences.
Demo site:  https://msa.nya.one
Relates to #124 
Resolve #56

### CODE REVIEW

**Comment by mkg20001** [comment]
Any chance to get this merged soon?

**Comment by ptman** [comment]
this would be great

**Comment by TafkaMax** [comment]
Hi

When I have a SSO configured and I also have a local administrator account, the login option is grayed out.

image

I presume that the UI gets some data from my homeserver and it sees that SSO is enabled, then it grays out the other option.

**Comment by Candinya** [comment]
Matrix synapse seems to disable password login when SSO is enabled. The password sign in function is only enabled when password authentication ("m.login.password") is enabled, which you can check all sign-in methods at `https://synapse.your.ltd/_matrix/client/r0/login`

(codes refer to https://github.com/Awesome-Technologies/synapse-admin/pull/196/files#diff-32a75d5d1a107623e923d7758d1c6ed3b5da0e57a33d5d049f4050adf9775ccfR246

**Comment by TafkaMax** [comment]
Hmm.

https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#password_config

```
enabled: Defaults to true. Set to false to disable password authentication. Set to only_for_reauth to allow users with existing passwords to use them to log in and reauthenticate, whilst preventing new users from setting passwords.

When the option is only_for_reauth it should be visible. 

Although the documentation is not precise as documented in this synapse github issue: https://github.com/matrix-org/synapse/issues/14686

**Pull request merged**
