### PR TITLE
Add management of devices to EditUser

### PR DESCRIPTION
**Pull request by dklimpel**
Allows to view user devices and logout individual devices from
those. Add a new tab to UserEdit (detail view).

### CODE REVIEW

**Comment by awesome-manuel** [comment]
Which version of Synapse is required to make this work?

**Comment by dklimpel** [comment]
> Which version of Synapse is required to make this work?

Synapse v.1.15.0
https://github.com/matrix-org/synapse/releases/tag/v1.15.0

**Comment by awesome-manuel** [comment]
@dklimpel I have a local rewrite of this change, so ne need to keep this PR updated.
I want to do a few things differently in the dataProvider. Those references should use `ReferenceManyField` as this is the right component for a 1:M relationship (`ReferenceField` is for 1:1 or M:1).

**Comment by dklimpel** [comment]
Merged https://github.com/Awesome-Technologies/synapse-admin/commit/314906657f4e69f0d5e2d776cb65912208e74af2

**Pull request closed without merging**
