### PR TITLE
Add locked status to users

### PR DESCRIPTION
**Pull request by dklimpel**
New in Synapse 1.91.0 (user details) and 1.93.0 (user list).

### CODE REVIEW

**Comment by dklimpel** [comment]
Related to:
- #403

**Comment by awesome-manuel** [comment]
Please add new translations also to `src/i18n/index.d.ts`. If you can't provide translations for all languages make them optional.

**Comment by dklimpel** [comment]
If I am add only one, the pipline is always failing.

**Comment by awesome-manuel** [comment]
> If I am add only one, the pipline is always failing.

Ah, sorry. Some fields were missing in the `index.d.ts`. Please merge latest master.

**Comment by awesome-manuel** [comment]
@hanadi92 I think this one had no merge conflicts when I reviewed it. Also it properly updates the README.md.
You're free to update #403 if you think something is missing.

**Pull request merged**
