### PR TITLE
Post react-admin upgrade tasks

### PR DESCRIPTION
**Pull request by dklimpel**
Some findings and open migration tasks from: https://marmelab.com/react-admin/Upgrade.html

### CODE REVIEW

**Comment by awesome-manuel** [comment]
Any special reason why you would like to remove the props?

**Comment by dklimpel** [comment]
In my opinion they not needed anymore. https://marmelab.com/react-admin/Upgrade.html#all-crud-views

**Comment by awesome-manuel** [comment]
> In my opinion they not needed anymore. https://marmelab.com/react-admin/Upgrade.html#all-crud-views

Not strictly needed, that's right. But the components (e.g. List) still recognize a lot of props that can be changed from outside. So our components are also more generic if we still pass all those props.

The general direction will be to split synapse-admin into several sub-packages, so that they can be reused in other react-admin applications.

**Comment by dklimpel** [comment]
I have finish this. Im not sure if I can resolf the merge conflicts. I am not know what is your directions to `props` and dataProvider (`previousData` vs `meta`).

**Comment by dklimpel** [comment]
> Not strictly needed, that's right. But the components (e.g. List) still recognize a lot of props that can be changed from outside. So our components are also more generic if we still pass all those props.

I am not a fan of prophylactically defining variables when they are not needed. Instead of specifying them across the board, in future they should be specified where they are needed.

**Comment by awesome-manuel** [comment]
Everything should be merged with 3adc6b4663ec741176389f6ecb70112bc7d058e3

**Comment by dklimpel** [comment]
There were more changes like deprecated[ `alwaysEnableSaveButton` ](https://marmelab.com/react-admin/Upgrade.html#toolbar-props-have-changed)

**Pull request closed without merging**
